export interface Profile {
  id: string;
  name: string;
  age: number;
  city: string;
  photos: string[];
  bio: string;
  interests: string[];
  habits: { smoking: boolean; drinking: boolean };
  work?: string;
  company?: string;
  school?: string;
  isMatch?: boolean;
}

export interface Message {
  id: string;
  senderId: string;
  text: string;
  timestamp: Date;
}

export interface Chat {
  id: string;
  matchId: string;
  messages: Message[];
  lastMessage?: Message;
  unreadCount: number;
}

export const mockProfiles: Profile[] = [
  {
    id: '1',
    name: 'Emma',
    age: 24,
    city: 'San Francisco',
    photos: ['/young-woman-smiling-outdoors.png'],
    bio: 'Love hiking and trying new coffee shops. Looking for someone to explore the city with!',
    interests: ['hiking', 'coffee', 'photography', 'travel', 'yoga'],
    habits: { smoking: false, drinking: true },
    work: 'Software Engineer',
    company: 'Tech Startup',
    isMatch: true,
  },
  {
    id: '2',
    name: 'Alex',
    age: 27,
    city: 'San Francisco',
    photos: ['/smiling-bearded-man.png'],
    bio: 'Musician by night, developer by day. Always up for live music and good food.',
    interests: ['music', 'cooking', 'concerts', 'guitar', 'craft beer'],
    habits: { smoking: false, drinking: true },
    work: 'Full Stack Developer',
    company: 'Music Tech',
    isMatch: true,
  },
  {
    id: '3',
    name: 'Maya',
    age: 22,
    city: 'San Francisco',
    photos: ['/young-woman-with-curly-hair-laughing.png'],
    bio: 'Art student who loves painting and weekend farmers markets.',
    interests: [
      'art',
      'painting',
      'farmers markets',
      'vintage shopping',
      'indie films',
    ],
    habits: { smoking: false, drinking: false },
    school: 'SF Art Institute',
    isMatch: false,
  },
  {
    id: '4',
    name: 'Jordan',
    age: 29,
    city: 'San Francisco',
    photos: ['/athletic-person-rock-climbing.png'],
    bio: "Rock climbing enthusiast and weekend warrior. Let's adventure together!",
    interests: [
      'rock climbing',
      'hiking',
      'camping',
      'fitness',
      'adventure sports',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Physical Therapist',
    company: 'Sports Medicine Clinic',
    isMatch: true,
  },
  {
    id: '5',
    name: 'Sophia',
    age: 26,
    city: 'San Francisco',
    photos: ['/smiling-dark-haired-woman.png'],
    bio: 'Yoga instructor and wellness coach. Passionate about mindful living and good vibes.',
    interests: ['yoga', 'meditation', 'wellness', 'reading', 'dancing'],
    habits: { smoking: false, drinking: false },
    work: 'Yoga Instructor',
    company: 'Mindful Studio',
    isMatch: true,
  },
  {
    id: '6',
    name: 'Marcus',
    age: 31,
    city: 'San Francisco',
    photos: ['/professional-man-casual.png'],
    bio: "Chef who loves experimenting with fusion cuisine. Let's cook something amazing together!",
    interests: [
      'cooking',
      'wine tasting',
      'travel',
      'food photography',
      'farmers markets',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Executive Chef',
    company: 'Fusion Restaurant',
    isMatch: false,
  },
  {
    id: '7',
    name: 'Zoe',
    age: 23,
    city: 'San Francisco',
    photos: ['/young-woman-with-blonde-hair-outdoors.png'],
    bio: 'Marine biology student fascinated by ocean conservation. Beach walks are my therapy.',
    interests: [
      'marine biology',
      'surfing',
      'environmental activism',
      'beach volleyball',
      'photography',
    ],
    habits: { smoking: false, drinking: true },
    school: 'UC San Francisco',
    isMatch: false,
  },
  {
    id: '8',
    name: 'David',
    age: 28,
    city: 'San Francisco',
    photos: ['/man-with-glasses-reading-book.png'],
    bio: 'Bookworm and coffee addict. Always looking for the next great novel recommendation.',
    interests: ['reading', 'coffee', 'writing', 'board games', 'indie films'],
    habits: { smoking: false, drinking: false },
    work: 'Technical Writer',
    company: 'Publishing House',
    isMatch: true,
  },
  {
    id: '9',
    name: 'Isabella',
    age: 25,
    city: 'San Francisco',
    photos: ['/woman-with-red-hair-laughing.png'],
    bio: 'Fashion designer with a passion for sustainable clothing. Style meets conscience.',
    interests: [
      'fashion design',
      'sustainability',
      'art',
      'vintage shopping',
      'cycling',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Fashion Designer',
    company: 'Eco Fashion Co',
    isMatch: false,
  },
  {
    id: '10',
    name: 'Ryan',
    age: 30,
    city: 'San Francisco',
    photos: ['/athletic-man-playing-basketball.png'],
    bio: 'Basketball coach and fitness enthusiast. Believe in pushing limits and having fun.',
    interests: [
      'basketball',
      'fitness',
      'coaching',
      'sports',
      'healthy eating',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Basketball Coach',
    company: 'Community Sports Center',
    isMatch: false,
  },
  {
    id: '11',
    name: 'Aria',
    age: 24,
    city: 'San Francisco',
    photos: ['/woman-playing-guitar.png'],
    bio: 'Singer-songwriter chasing dreams one melody at a time. Music is my universal language.',
    interests: ['music', 'singing', 'guitar', 'songwriting', 'concerts'],
    habits: { smoking: false, drinking: true },
    work: 'Musician',
    company: 'Independent Artist',
    isMatch: false,
  },
  {
    id: '12',
    name: 'Ethan',
    age: 27,
    city: 'San Francisco',
    photos: ['/man-hiking-in-mountains.png'],
    bio: "Adventure photographer capturing life's beautiful moments. Let's explore together!",
    interests: [
      'photography',
      'hiking',
      'travel',
      'adventure sports',
      'camping',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Photographer',
    company: 'Freelance',
    isMatch: false,
  },
  {
    id: '13',
    name: 'Luna',
    age: 26,
    city: 'San Francisco',
    photos: ['/colorful-hair-painting.png'],
    bio: 'Digital artist and creative soul. I see the world in colors and possibilities.',
    interests: ['digital art', 'painting', 'creativity', 'gaming', 'anime'],
    habits: { smoking: false, drinking: false },
    work: 'Digital Artist',
    company: 'Creative Agency',
    isMatch: false,
  },
  {
    id: '14',
    name: 'Carlos',
    age: 32,
    city: 'San Francisco',
    photos: ['/man-dancing-salsa.png'],
    bio: 'Salsa instructor who believes life is better with rhythm. Dance your way into my heart!',
    interests: ['dancing', 'salsa', 'music', 'teaching', 'latin culture'],
    habits: { smoking: false, drinking: true },
    work: 'Dance Instructor',
    company: 'Latin Dance Studio',
    isMatch: false,
  },
  {
    id: '15',
    name: 'Chloe',
    age: 23,
    city: 'San Francisco',
    photos: ['/young-woman-volunteering.png'],
    bio: 'Psychology student passionate about mental health advocacy. Kindness changes everything.',
    interests: [
      'psychology',
      'volunteering',
      'mental health',
      'reading',
      'meditation',
    ],
    habits: { smoking: false, drinking: false },
    school: 'Stanford University',
    isMatch: false,
  },
  {
    id: '16',
    name: 'Jake',
    age: 29,
    city: 'San Francisco',
    photos: ['/man-working-on-motorcycle.png'],
    bio: "Motorcycle mechanic with a love for vintage bikes. Life's a journey, enjoy the ride.",
    interests: [
      'motorcycles',
      'mechanics',
      'vintage restoration',
      'road trips',
      'craft beer',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Motorcycle Mechanic',
    company: 'Custom Bike Shop',
    isMatch: false,
  },
  {
    id: '17',
    name: 'Ava',
    age: 25,
    city: 'San Francisco',
    photos: ['/woman-in-laboratory.png'],
    bio: 'Biotech researcher working on the future of medicine. Science geek with a big heart.',
    interests: [
      'science',
      'research',
      'biotechnology',
      'hiking',
      'wine tasting',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Research Scientist',
    company: 'Biotech Startup',
    isMatch: false,
  },
  {
    id: '18',
    name: 'Noah',
    age: 28,
    city: 'San Francisco',
    photos: ['/man-teaching-children.png'],
    bio: 'Elementary teacher who believes in nurturing young minds. Patience and humor are my superpowers.',
    interests: [
      'teaching',
      'children',
      'education',
      'board games',
      'volunteering',
    ],
    habits: { smoking: false, drinking: false },
    work: 'Elementary Teacher',
    company: 'Public School District',
    isMatch: false,
  },
  {
    id: '19',
    name: 'Mia',
    age: 27,
    city: 'San Francisco',
    photos: ['/woman-rock-climbing.png'],
    bio: 'Adventure therapist combining my love for outdoors with helping others heal.',
    interests: [
      'rock climbing',
      'therapy',
      'outdoor adventures',
      'mindfulness',
      'fitness',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Adventure Therapist',
    company: 'Wellness Center',
    isMatch: false,
  },
  {
    id: '20',
    name: 'Leo',
    age: 31,
    city: 'San Francisco',
    photos: ['/man-playing-piano.png'],
    bio: 'Jazz pianist who finds magic in improvisation. Life, like music, is best when spontaneous.',
    interests: [
      'jazz',
      'piano',
      'music composition',
      'vinyl records',
      'coffee',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Jazz Musician',
    company: 'Local Jazz Club',
    isMatch: false,
  },
  {
    id: '21',
    name: 'Grace',
    age: 24,
    city: 'San Francisco',
    photos: ['/woman-gardening.png'],
    bio: 'Urban gardener growing community connections one plant at a time. Green thumb, big dreams.',
    interests: [
      'gardening',
      'sustainability',
      'community building',
      'farmers markets',
      'cooking',
    ],
    habits: { smoking: false, drinking: false },
    work: 'Urban Farmer',
    company: 'Community Garden Project',
    isMatch: false,
  },
  {
    id: '22',
    name: 'Oliver',
    age: 26,
    city: 'San Francisco',
    photos: ['/man-coding-on-laptop.png'],
    bio: 'Full-stack developer building apps that make a difference. Code by day, game by night.',
    interests: [
      'programming',
      'gaming',
      'technology',
      'board games',
      'craft beer',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Software Developer',
    company: 'Social Impact Startup',
    isMatch: false,
  },
  {
    id: '23',
    name: 'Lily',
    age: 25,
    city: 'San Francisco',
    photos: ['/woman-doing-yoga-on-beach.png'],
    bio: 'Travel blogger documenting adventures around the world. Next destination: your heart?',
    interests: [
      'travel',
      'blogging',
      'photography',
      'yoga',
      'cultural exploration',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Travel Blogger',
    company: 'Freelance',
    isMatch: false,
  },
  {
    id: '24',
    name: 'Mason',
    age: 33,
    city: 'San Francisco',
    photos: ['/placeholder.svg?height=600&width=400'],
    bio: "Coffee roaster and café owner. Life's too short for bad coffee and boring conversations.",
    interests: [
      'coffee',
      'entrepreneurship',
      'roasting',
      'cycling',
      'local business',
    ],
    habits: { smoking: false, drinking: true },
    work: 'Café Owner',
    company: 'Artisan Coffee Co',
    isMatch: false,
  },
];

export const mockChats: Chat[] = [
  {
    id: '1',
    matchId: '1',
    messages: [
      {
        id: '1',
        senderId: '1',
        text: 'Hey! I saw you love hiking too. Have you been to Muir Woods?',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: '2',
        senderId: 'me',
        text: "Yes! It's amazing there. I went last weekend actually.",
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        id: '3',
        senderId: '1',
        text: "That's awesome! I'm planning to go this Saturday. Want to join?",
        timestamp: new Date(Date.now() - 30 * 60 * 1000),
      },
    ],
    unreadCount: 1,
  },
  {
    id: '2',
    matchId: '2',
    messages: [
      {
        id: '4',
        senderId: '2',
        text: "Love your taste in music! Saw you're into indie rock.",
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      },
      {
        id: '5',
        senderId: 'me',
        text: 'Thanks! Do you play any instruments?',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        id: '6',
        senderId: '2',
        text: 'Yeah, I play guitar and some piano. Been working on some new songs lately.',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: '7',
        senderId: 'me',
        text: "That's so cool! I'd love to hear them sometime.",
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        id: '8',
        senderId: '2',
        text: "Definitely! There's this great venue downtown where I sometimes perform. Maybe we could check it out together?",
        timestamp: new Date(Date.now() - 45 * 60 * 60 * 1000),
      },
    ],
    unreadCount: 0,
  },
  {
    id: '3',
    matchId: '4',
    messages: [
      {
        id: '9',
        senderId: '4',
        text: 'Rock climbing buddy! 🧗‍♀️ I see we have similar interests',
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        id: '10',
        senderId: 'me',
        text: "Yes! I'm always looking for climbing partners. What's your favorite spot?",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
      },
      {
        id: '11',
        senderId: '4',
        text: 'I love Castle Rock! The routes there are challenging but so rewarding.',
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      },
      {
        id: '12',
        senderId: 'me',
        text: 'Castle Rock is amazing! I was there two weeks ago. The sunset views are incredible.',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        id: '13',
        senderId: '4',
        text: "Right?! The golden hour lighting makes everything look magical. I'm planning a trip there this weekend if you're interested?",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: '14',
        senderId: 'me',
        text: "That sounds perfect! I'd love to join. What time were you thinking?",
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        id: '15',
        senderId: '4',
        text: 'How about we meet at 8 AM? That way we can get some good climbing in before it gets too crowded.',
        timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000),
      },
    ],
    unreadCount: 1,
  },
  {
    id: '4',
    matchId: '5',
    messages: [
      {
        id: '16',
        senderId: '5',
        text: "Namaste! 🙏 I noticed you're into yoga too. What's your favorite style?",
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
      },
      {
        id: '17',
        senderId: 'me',
        text: "Hi! I love vinyasa flow. There's something so meditative about linking breath with movement.",
        timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
      },
      {
        id: '18',
        senderId: '5',
        text: "Yes! That's exactly how I feel. I teach vinyasa classes at my studio. You should come by sometime!",
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        id: '19',
        senderId: 'me',
        text: "That would be amazing! I've been looking for a new studio. What's the vibe like there?",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
      },
      {
        id: '20',
        senderId: '5',
        text: "It's very welcoming and inclusive. We focus on mindful practice rather than perfect poses. Community over competition, you know?",
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      },
      {
        id: '21',
        senderId: 'me',
        text: "That sounds exactly like what I'm looking for. When's your next class?",
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        id: '22',
        senderId: '5',
        text: "I have a sunset flow class tomorrow at 6 PM. It's on the rooftop with city views - absolutely magical!",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: '23',
        senderId: 'me',
        text: 'Rooftop yoga with sunset views? Count me in! Should I bring my own mat?',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        id: '24',
        senderId: '5',
        text: 'We have mats available, but feel free to bring yours if you prefer. Looking forward to practicing with you! ✨',
        timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000),
      },
    ],
    unreadCount: 1,
  },
];

export const interestOptions = [
  'hiking',
  'coffee',
  'photography',
  'travel',
  'yoga',
  'music',
  'cooking',
  'concerts',
  'guitar',
  'craft beer',
  'art',
  'painting',
  'farmers markets',
  'vintage shopping',
  'indie films',
  'rock climbing',
  'camping',
  'fitness',
  'adventure sports',
  'reading',
  'dancing',
  'wine tasting',
  'board games',
  'cycling',
  'surfing',
  'meditation',
  'volunteering',
];

// Fake user for testing - can be easily removed
export interface FakeUser {
  id: string;
  email: string;
  name: string;
  age: number;
  city: string;
  photos: string[];
  bio: string;
  interests: string[];
  habits: { smoking: boolean; drinking: boolean };
  work?: string;
  company?: string;
  school?: string;
  onboardingComplete: boolean;
  isMatch?: boolean;
}

export const fakeUser: FakeUser = {
  id: 'fake-user-123',
  email: 'test@example.com',
  name: 'Alex Chen',
  age: 26,
  city: 'San Francisco',
  photos: ['/placeholder-user.jpg'],
  bio: 'Software developer who loves hiking, coffee, and trying new restaurants. Looking for someone to explore the city with!',
  interests: ['hiking', 'coffee', 'programming', 'travel', 'food'],
  habits: { smoking: false, drinking: true },
  work: 'Software Engineer',
  company: 'Tech Company',
  onboardingComplete: true,
  isMatch: false,
};
